### ISSUE TITLE
Can't build working HTML-mail in draft mode

### ISSUE THREAD

**Issue by SpikeBerlin** [Sicos1977/MsgKit#16]
I can't create working msg-files with BodyHtml and mail in draft mode.
The result in Outlook is an mail, where not html is available.
Is draft = false, all is ok ...

**Comment by Sicos1977** [comment]
This is normal Outlook behavior. Nothing that I can change. -------- Oorspronkelijk bericht --------Onderwerp: [Sicos1977/MsgKit] Can't build working HTML-mail in draft mode (#16)Van: SpikeBerlin Aan: Sicos1977/MsgKit Cc: Subscribed I can't create working msg-files with BodyHtml and mail in draft mode.
The result in Outlook is an mail, where not html is available.
Is draft = false, all is ok ...

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Sicos1977/MsgKit","title":"Sicos1977/MsgKit","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Sicos1977/MsgKit"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Can't build working HTML-mail in draft mode (#16)"}],"action":{"name":"View Issue","url":"https://github.com/Sicos1977/MsgKit/issues/16"}}}

**Comment by joaonoch** [comment]
Normal? How to create html drafts then?

**Comment by joaonoch** [comment]
@Sicos1977 Please Clarify. Are there any alternative technologies?

**Comment by Sicos1977** [comment]
To make a draft mail work you need to embed the HTML into RTF and add that RTF to the message file. HTML embedded into RTF is something that currently is not supported in MsgKit since it is a lot of work to build that.

**Comment by joaonoch** [comment]
@Sicos1977 Thanks, I've found an alternative technology that supports this (Aspose for .NET)

**Comment by Sicos1977** [comment]
Glad that you found another alternative.

**Comment by Sicos1977** [comment]
I found a highly experimental workaround to support HTML embedded into RTF when the Email is set to draft. See this commit --? https://github.com/Sicos1977/MsgKit/commit/081e138d7f84b9e08adf2b8bf71a184c829f737d

Just try it out an let me know if it works for you.
