### ISSUE TITLE
Create a task

### ISSUE THREAD

**Issue by nicrf** [Sicos1977/MsgKit#23]
How I can  create a task with this librairy?

**Comment by Sicos1977** [comment]
That is not yet implemented. Feel free to add it. Verzonden vanaf mijn Huawei mobiele telefoon-------- Oorspronkelijk bericht --------Onderwerp: [Sicos1977/MsgKit] Create a task (#23)Van: nicrf Aan: Sicos1977/MsgKit Cc: Subscribed How I can  create a task with this librairy?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Sicos1977/MsgKit","title":"Sicos1977/MsgKit","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Sicos1977/MsgKit"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Create a task (#23)"}],"action":{"name":"View Issue","url":"https://github.com/Sicos1977/MsgKit/issues/23"}}}

**Comment by nicrf** [comment]
I will try!

**Comment by nicrf** [comment]
Do you have a tool to check the msg file?

**Comment by Sicos1977** [comment]
You can use outlookSpy for that, you can try it out for 30 days.

http://www.dimastr.com/outspy/home.htm

**Comment by Sicos1977** [comment]
I made preparations to add task support --> https://github.com/Sicos1977/MsgKit/commit/bb8f8632f1e97b75bf76ca5cc35ec55a5797d32c

**Comment by nicrf** [comment]
Ho, good, I will merge my code on it.

**Comment by nicrf** [comment]
Do you have a helper class to build a RecurrencePattern Structure ([MS-OXOCAL] 2.2.1.44.1 ) for PidLidTaskRecurrence.

[Task.zip](https://github.com/Sicos1977/MsgKit/files/1519050/Task.zip)

**Comment by Sicos1977** [comment]
No I don't. But it does not seem to hard to build that. I can build that for you if you want but that will be this weekend or next week. At the moment I'm a little bit busy with something else.

I added your task enums to the msgkit code base. I refactored them a little bit so that they are inline with the rest of the code style in the MSGKit project.

Greetings,
Kees van Spelde

**Comment by Sicos1977** [comment]
I already added the needed enum files for the RecurrencePattern

**Comment by nicrf** [comment]
Hi, I merged with your standart, I will try to do the reccurent.

[Task.zip](https://github.com/Sicos1977/MsgKit/files/1527955/Task.zip)

**Comment by nicrf** [comment]
Hi, 

It seems that the change of class does not happen:
`public class Task : Email
...
private new void WriteToStorage()
        {
            Class = MessageClass.IPM_Task;`

My email open in IMP.Note
![2017-12-04_12h34_53](https://user-images.githubusercontent.com/29955546/33567057-edd34b64-d8ef-11e7-8da8-1bebff90575e.png)

If I force to IPM.Task, my email work.

**Comment by nicrf** [comment]
Hello,

I finished writing the rough draft. I got some weird error on my date, I will check this next time : 
![2017-12-04_20h48_57](https://user-images.githubusercontent.com/29955546/33585991-11d342d6-d935-11e7-9c23-f0da687f640e.png)

**Comment by nicrf** [comment]
Hi,

I have tested many thing, but I find something weird:
I want to add two date in a month pattern, like 10 and 20 :
![2017-12-05_22h18_10](https://user-images.githubusercontent.com/29955546/33642983-92c76af4-da0a-11e7-962f-2dc197d9dcc2.png)

And I got this : 
![2017-12-05_22h25_41](https://user-images.githubusercontent.com/29955546/33643151-56659490-da0b-11e7-9dd9-6e7d0c773f43.png)


Do you have an idea?

**Comment by Sicos1977** [comment]
I will look into your code this weekend.

**Comment by nicrf** [comment]
Hi,

Did you get the time to chek it?

**Comment by Sicos1977** [comment]
I completely forgot this. I'll add it on my todo list again

**Comment by auctionsjeff** [comment]
Very awesome project! The Task piece is great too! @nicrf, would you consider updating the README.md in your PR with a quick example for creating a Task, and maybe even one for creating a recurring Task (assuming the quirks get worked out)? I'm curious to see if this would also work for making recurring appointments...

Thanks for your hard work guys!
Jeff
