### ISSUE TITLE
Proper way to send msg

### ISSUE THREAD

**Issue by dmarlow** [Sicos1977/MsgKit#27]
What are the options for sending a msg created with MsgKit? Is there a way to use the SmtpClient without adding the file as an attachment? I'm trying to replicate sending an appointment just like Outlook would without having Outlook installed. The only thing I can think of is to put it into a folder where an SMTP server (IIS) takes the files and sends them automatically, but I'd prefer to use SmtpClient if possible.

**Comment by Sicos1977** [comment]
The only option to send an msg file and keep it intact is to add it as an attachment. The reason is that an msg file is a container format for Outlook invented by Microsoft. If you want to send an appointment then you have to convert it to ICS format. This is also what Outlook is doing when sending the appointment to someone outside of your organisation.

**Comment by Sicos1977** [comment]
Are you sending the appointments to someone inside your organisation?

**Comment by dmarlow** [comment]
No. I did just come across this and will try a few things out.

https://stackoverflow.com/questions/18827268/send-an-actual-outlook-meeting-request-without-using-outlook#
