### ISSUE TITLE
Oft

### ISSUE THREAD

**Issue by Narfix** [Sicos1977/MsgKit#31]
Hello !

Could MsgKit be used to generate .oft files ?

Thanks !

**Comment by Sicos1977** [comment]
No, it only produces msg files

**Comment by ChrisKoenig** [comment]
I am in the same situation and need to generate OFTs for our team to use. Although simply saving the MSG locally as an OFT file works when you have no inline graphics or HTML formatting in your email, I couldn't get it to work otherwise.

What I ended up doing was generating an MSG, and then instructing the team using these dynamically generated emails to just "open and forward" the mail, manually fixing the Subject line (i.e. removing the FW:) and manually removing the Forward Header.

Not an optimal solution, but that's the best I could get with the toolkit at this time.

**Comment by Sicos1977** [comment]
Your welcome to modify the code so that it also can make OFT files. OFT files are just outlook templates and almost use all the same properties then a MSG file
