### ISSUE TITLE
Msg file Subject Preview 

### ISSUE THREAD

**Issue by priuser** [Sicos1977/MsgKit#65]
Hi, with ref. to my previous thread#64.

After converting to EML and loading it in Outlook 365, the email preview pane says "No preview available", what would be causing this issue?  

TIA

**Comment by Sicos1977** [comment]
I have no idea, to figure out why outlook 365 isn't showing a preview I need to have an e-mail that doesn't work and an e-mail that works so that I can see what the differences are between those e-mails.

It would be nice if the e-mails are the same because that makes it easier for me to figure out what the differences are. If you have them you can send them to my e-mail adres sicos2002@hotmail.com

**Comment by Sicos1977** [comment]
At the moment I'm a little bit busy but it is still on my to do list

**Comment by aravind1078** [comment]
@Sicos1977  outlook doesn't pick the date(date on the preview) as well i don't know why. but it does show the date when we completely open a particular mail

**Comment by Sicos1977** [comment]
Sorry for the very late respone, can you send me the e-mail that is giving this problem and add some screenshots about what you are seeing?
