### ISSUE TITLE
How to show the Email object in Outlook composing mode

### ISSUE THREAD

**Issue by nologinatgit** [Sicos1977/MsgKit#68]
I have created a new email object but instead of opening the saved  and **readonly msg format**, I'd like to open it in Outlook as a currently composing email.

Can I do it with this library? Maybe I could use the Stream?

**Comment by Sicos1977** [comment]
Yes... Set the draft flag to trueOp 3 mrt. 2020 21:15 schreef András <notifications@github.com>:I have created a new email object but instead of opening the saved  and readonly msg format, I'd like to open it in Outlook as a currently composing email.
Can I do it with this library? Maybe I could use the Stream?

**Comment by nologinatgit** [comment]
Thanks, it works 👍
