### ISSUE TITLE
Convert eml to msg error on missing picture from signature

### ISSUE THREAD

**Issue by iviamandi** [Sicos1977/MsgKit#77]
For a  message which contains a missing picture in sender signature, MsgKit.Converter.ConvertEmlToMsg() throws:

System.ArgumentNullException: The content id cannot be empty when isInline is set to true
Parameter name: contentId
   at MsgKit.Attachment..ctor(Stream stream, String fileName, DateTime creationTime, DateTime lastModificationTime, AttachmentType type, Int64 renderingPosition, Boolean isInline, String contentId, Boolean isContactPhoto)
   at MsgKit.Attachments.Add(Stream stream, String fileName, Int64 renderingPosition, Boolean isInline, String contentId)
   at MsgKit.Converter.ConvertEmlToMsg(Stream emlFile, Stream msgFile)
   at MsgKit.Converter.ConvertEmlToMsg(String emlFileName, String msgFileName)

**Comment by Sicos1977** [comment]
Can you sent me this file? If so then zip the file before sending it to sicos2002@hotmail.com

**Comment by iviamandi** [comment]
Sorry for the delay, I sent you the message.

**Comment by sageddes** [comment]
Greetings, we have run across the same issue and in our case, it appears to happen when the Content ID is missing from the eml file.  While I realize having a Content Id is the standard for identifying inline attachments, some email clients seem to allow inline images without including the Content Id.  

Instead of throwing the exception in the Attachments constructor, I would recommend changing the Converter to check for bodyPart.ContentId != null when setting the inline variable prior to the call.  

```
var inline = bodyPart.ContentDisposition != null &&
             bodyPart.ContentId != null &&
             bodyPart.ContentDisposition.Disposition.Equals("inline",
                            StringComparison.InvariantCultureIgnoreCase);
```

From my testing, this allows the process to complete, just with a missing attachment instead of failure.  Please let me/us know your thoughts on the matter.

**Comment by Sicos1977** [comment]
I implemented it ... sorry for the very late response.

**Comment by Sicos1977** [comment]
I will add the check

**Comment by Sicos1977** [comment]
Added
